package com.autentia.tnt.binnacle.repositories

import com.autentia.tnt.binnacle.entities.*
import com.autentia.tnt.binnacle.repositories.predicates.ActivityPredicates
import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import jakarta.inject.Inject
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.*
import java.time.LocalDate
import java.util.*


@MicronautTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ActivityMissingEvidenceSpecificationIT {

    private companion object {
        // Everything for organization with ID = 3

        // Roles for project with id = 6
        private val project_1_role_weekly = 6L
        private val project_1_role_once = 7L

        // Roles for project with id = 7
        private val project_2_role_weekly = 8L
        private val project_2_role_once = 9L
        private val project_2_role_none = 10L

        // Users
        private val test_user_1 = 11L
        private val test_user_2 = 12L

        // Fixed data
        private val today = LocalDate.now()
        private val yesterday = today.minusDays(1)
    }

    // Data test
    private lateinit var project1RoleWeekly: ProjectRole
    private lateinit var project1RoleOnce: ProjectRole

    private lateinit var project2RoleWeekly: ProjectRole
    private lateinit var project2RoleOnce: ProjectRole
    private lateinit var project2RoleNone: ProjectRole

    @Inject
    private lateinit var projectRoleDao: ProjectRoleDao

    @Inject
    private lateinit var activityDao: ActivityDao

    @BeforeAll
    fun `obtain data test references`() {
        project1RoleWeekly = projectRoleDao.findById(project_1_role_weekly).orElseThrow { IllegalStateException() }
        project1RoleOnce = projectRoleDao.findById(project_1_role_once).orElseThrow { IllegalStateException() }

        project2RoleWeekly = projectRoleDao.findById(project_2_role_weekly).orElseThrow { IllegalStateException() }
        project2RoleOnce = projectRoleDao.findById(project_2_role_once).orElseThrow { IllegalStateException() }
        project2RoleNone = projectRoleDao.findById(project_2_role_none).orElseThrow { IllegalStateException() }
    }


    @Test
    fun `should find activities without evidence and required evidence once`() {
        // Setup
        val activityWithoutEvidence = Activity(
            start = yesterday.atTime(8, 0, 0),
            end = yesterday.atTime(17, 0, 0),
            duration = 540,
            description = "Test activity 2",
            projectRole = project1RoleOnce,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )

        activityDao.save(activityWithoutEvidence)

        // Search
        val predicate = ActivityPredicates.missingEvidenceOnce()
        val result = activityDao.findAll(predicate)

        assertThat(result).containsExactlyInAnyOrder(activityWithoutEvidence)
    }

    @Test
    fun `should not find activities that not require evidence once`() {
        val activityRequiresWeekly = Activity(
            start = yesterday.atTime(8, 0, 0),
            end = yesterday.atTime(17, 0, 0),
            duration = 540,
            description = "Test activity 4",
            projectRole = project2RoleWeekly,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )
        val activityNotRequireEvidence = Activity(
            start = yesterday.atTime(8, 0, 0),
            end = yesterday.atTime(17, 0, 0),
            duration = 540,
            description = "Test activity 5",
            projectRole = project2RoleNone,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )

        activityDao.saveAll(listOf(activityRequiresWeekly, activityNotRequireEvidence))

        val predicate = ActivityPredicates.missingEvidenceOnce()
        val activities = activityDao.findAll(predicate)

        assertThat(activities).isEmpty()
    }

    @Test
    fun `should not find activities that have evidence with required once`() {
        val activityWithEvidence = Activity(
            start = yesterday.atTime(8, 0, 0),
            end = yesterday.atTime(17, 0, 0),
            duration = 540,
            description = "Test activity 3",
            projectRole = project1RoleOnce,
            userId = test_user_2,
            billable = false,
            hasEvidences = true,
            approvalState = ApprovalState.PENDING
        )
        val activityWithAutogeneratedEvidence = Activity(
            start = yesterday.atTime(8, 0, 0),
            end = yesterday.atTime(17, 0, 0),
            duration = 540,
            description = "###Autocreated evidence###\n(DO NOT DELETE)\n ETC. ETC.",
            projectRole = project1RoleOnce,
            userId = test_user_2,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )

        activityDao.saveAll(listOf(activityWithEvidence, activityWithAutogeneratedEvidence))

        val predicate = ActivityPredicates.missingEvidenceOnce()
        val activities = activityDao.findAll(predicate)

        assertThat(activities).isEmpty()
    }

    @Test
    fun `should find activities missing evidence with required evidence weekly`() {
        val activityWithEvidence = Activity(
            start = today.atTime(8, 0, 0).minusDays(3),
            end = today.atTime(17, 0, 0).minusDays(3),
            duration = 540,
            description = "###Autocreated evidence###\n(DO NOT DELETE)\n ETC. ETC.",
            projectRole = project2RoleWeekly,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )
        val activityHasPreviousEvidence = Activity(
            start = today.atTime(8, 0, 0),
            end = today.atTime(17, 0, 0),
            duration = 540,
            description = "This should NOT be returned",
            projectRole = project2RoleWeekly,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )
        val activityEvidenceTooOld = Activity(
            start = today.atTime(8, 0, 0).minusDays(8),
            end = today.atTime(17, 0, 0).minusDays(8),
            duration = 540,
            description = "###Autocreated evidence###\n(DO NOT DELETE)\n ETC. ETC.",
            projectRole = project1RoleWeekly,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )
        val activityWithoutEvidence = Activity(
            start = today.atTime(8, 0, 0),
            end = today.atTime(17, 0, 0),
            duration = 540,
            description = "This should be returned",
            projectRole = project1RoleWeekly,
            userId = test_user_1,
            billable = false,
            hasEvidences = false,
            approvalState = ApprovalState.PENDING
        )
        
        activityDao.saveAll(
            listOf(
                activityWithEvidence,
                activityEvidenceTooOld,
                activityHasPreviousEvidence,
                activityWithoutEvidence,
            )
        )

        val predicate = ActivityPredicates.missingEvidenceWeekly()
        val results = activityDao.findAll(predicate)
        val expectedResults: List<Activity> = listOf(activityWithoutEvidence)

        assertThat(results).containsExactlyInAnyOrderElementsOf(expectedResults)
    }
}