ALTER TABLE Project ADD billingType VARCHAR(64) DEFAULT 'TIME_AND_MATERIALS' AFTER billable;
UPDATE Project SET billingType = 'NO_BILLABLE' WHERE billable = FALSE;
ALTER TABLE Project DROP COLUMN billable;

